pipeline {
    agent any
    tools {
        maven 'Maven3.9.9'  // The name you set in Jenkins Global Tool Configuration
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        stage('Complete') { 
            steps {
                echo 'Job Complete'
            }
        }
    }
}
